version: 2

builds:
  - binary: ccdc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
